id = "zed-mcshader"
name = "Language Server for Minecraft Shaderpacks"
description = "Iris GLSL shader pack support through vscode_mcshader."
version = "0.1.0"
schema_version = 1
authors = ["Luracasmus"]
repository = "https://github.com/Luracasmus/zed-mcshader"

[language_servers.vscode-mcshader]
name = "vscode-mcshader"
language = "GLSL"
